# Generated by Django 4.0.5 on 2022-06-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='shipment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipmentdetails'),
            preserve_default=False,
        ),
    ]
