# Generated by Django 4.0.5 on 2022-06-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_rename_traking_id_trackingdetails_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingdetails',
            old_name='traking_number',
            new_name='tracking_number',
        ),
    ]
