# Generated by Django 4.0.5 on 2022-06-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_rename_traking_number_trackingdetails_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingdetails',
            old_name='orgin',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='trackingdetails',
            old_name='Status',
            new_name='status',
        ),
    ]
